# Client-specific Bun configuration

[test]
# Test configuration for client
root = "./tests"
coverage = true
coverageThreshold = 0.6

# Development settings
[dev]
# Port for the dev server (Expo)
port = 8081