[mcp_servers.expo]
url = "https://mcp.expo.dev/mcp"

[mcp_servers.figma-desktop]
url = "http://127.0.0.1:3845/mcp"

[mcp_servers.ios-simulator]
command = "npx"
args = [
    "-y",
    "ios-simulator-mcp",
]

[mcp_servers.maestro]
command = "maestro"
args = ["mcp"]

[mcp_servers.mobile-mcp]
command = "npx"
args = [
    "-y",
    "@mobilenext/mobile-mcp@latest",
]

[mcp_servers.react-native-debugger-mcp]
command = "npx"
args = [
    "-y",
    "@twodoorsdev/react-native-debugger-mcp",
]
