version: '3.8'

# Development override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  redis:
    ports:
      - "6379:6379"
    environment:
      - REDIS_LOGLEVEL=debug

  # Development tools
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: whatsapp-ai-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - whatsapp-ai-network

networks:
  whatsapp-ai-network:
    driver: bridge