# mautrix-meta (Instagram) Configuration for Claire
# Documentation: https://docs.mau.fi/bridges/go/meta/config.html

homeserver:
    address: http://synapse:8008
    domain: claire.local

appservice:
    address: http://mautrix-instagram:29319
    hostname: 0.0.0.0
    port: 29319
    database:
        type: sqlite3-fk-wal
        uri: /data/mautrix-instagram.db
    id: instagram
    bot:
        username: metabot
        displayname: Instagram Bridge Bot
    as_token: JfIHXyofgCLVDfyfeDXFWtDMDDCRyBfsG5x7GLDXn4Ay0DwNYUQXH2YiTIogNul9
    hs_token: AnOjYg3WlsvlknIjIuanULCRpHVlFg7ncFakCAoDhRrn0YYYgKUMp7reNDNCUpkx

meta:
    mode: instagram

bridge:
    username_template: "meta_{{.}}"
    displayname_template: "{{.Name}} (IG)"
    command_prefix: "!ig"

    permissions:
        "*": relay
        "claire.local": user
        "@claire_bot:claire.local": admin

    private_chat_portal_meta: true

provisioning:
    shared_secret: "claire-instagram-bridge-secret-key-2026"

logging:
    min_level: info
    writers:
        - type: stdout
          format: pretty-colored
