import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { PageHero } from '@/components/site/PageHero';

const swatches = [['Ink', '#171914'], ['Paper', '#f8f5eb'], ['Lime', '#dfff64'], ['Mint', '#dff7e8'], ['Sky', '#dceeff'], ['Graphite', '#2c2f2a']];

export default function ComponentsPage() {
  return <main><PageHero eyebrow="COMPONENT KIT" title="A shared UI grammar for every Claire surface." intro="These are live website primitives today and the source of truth for equivalent mobile and desktop patterns as the design system migration continues." primary={{ label: 'Run Storybook', href: '/developers/docs/getting-started#storybook' }} /><section className="kit shell"><div className="kit-section"><h2>Color foundations</h2><div className="swatches">{swatches.map(([name, color]) => <div key={name}><span style={{ background: color }}></span><b>{name}</b><code>{color}</code></div>)}</div></div><div className="kit-section"><h2>Actions and states</h2><div className="component-stage"><Button href="#">Primary action</Button><Button href="#" tone="secondary">Secondary action</Button><Button href="#" tone="quiet">Quiet action</Button><Badge tone="lime">Available</Badge><Badge tone="blue">Beta</Badge><Badge>Planned</Badge></div></div><div className="kit-section"><h2>Surfaces</h2><div className="card-grid"><Card><span className="card-index">01</span><h3>Default card</h3><p>Neutral structure for content and navigation.</p></Card><Card tint="mint"><span className="card-index">02</span><h3>Supporting card</h3><p>Soft emphasis without competing with primary actions.</p></Card><Card tint="lime"><span className="card-index">03</span><h3>AI or action card</h3><p>Reserved for Claire intelligence and decisive moments.</p></Card></div></div><div className="kit-section"><h2>Usage rules</h2><div className="rule-grid"><p><b>Icons</b>24px Heroicons outline for navigation; 20px for compact controls; vendor marks only identify platforms.</p><p><b>Focus</b>Every interactive control receives a visible ink-and-lime focus ring and a minimum 44px target.</p><p><b>Emphasis</b>Lime is scarce. Use it for intelligence, selection, or conversion—not general decoration.</p><p><b>Copy</b>State current capability separately from roadmap, hosting requirements, and privacy guarantees.</p></div></div></section></main>;
}
