import { platformCatalog, platformCatalogVersion } from '../packages/platform-catalog/src/index';

const target = new URL('../apps/website/public/scripts/platform-catalog.js', import.meta.url);
const payload = {
  version: platformCatalogVersion,
  source: 'https://github.com/mautrix/docs/blob/master/bridges/SUMMARY.md',
  platforms: platformCatalog,
};

await Bun.write(
  target,
  `// Generated by bun run catalog:generate. Do not edit by hand.\nwindow.CLAIRE_PLATFORM_CATALOG = ${JSON.stringify(payload, null, 2)};\n`
);

console.log(`Generated ${platformCatalog.length} platform definitions.`);
