#!/usr/bin/env bun

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const name = process.argv[2] || 'my-plugin';
const slug = name.replace(/[^a-z0-9-]/gi, '-').toLowerCase();
const dir = join('examples/plugins', slug);

mkdirSync(join(dir, 'src'), { recursive: true });

writeFileSync(
  join(dir, 'package.json'),
  `${JSON.stringify(
    {
      name: `@claire/example-${slug}-plugin`,
      version: '0.1.0',
      private: true,
      license: 'Apache-2.0',
      type: 'module',
      main: 'src/index.ts',
      dependencies: { '@claire/plugin-sdk': 'workspace:*' },
    },
    null,
    2,
  )}\n`,
);

writeFileSync(
  join(dir, 'src/index.ts'),
  `import { createReceiptId, definePlugin } from '@claire/plugin-sdk';

export const plugin = definePlugin({
  manifest: {
    schemaVersion: '1',
    id: 'com.claire.example.${slug.replace(/-/g, '.')}',
    version: '0.1.0',
    name: ${JSON.stringify(name)},
    description: 'Local fixture plugin generated by bun run plugin:create.',
    publisher: {
      id: 'local',
      name: 'Local contributor',
      verification: 'private',
      website: 'https://github.com/l2succes/claire',
      privacyPolicyUrl: 'https://github.com/l2succes/claire/blob/main/SECURITY.md',
      supportUrl: 'https://github.com/l2succes/claire/discussions',
    },
    icon: { lightUrl: '/assets/brand/claire-app-icon.svg', sha256: '${'0'.repeat(64)}' },
    runtime: { kind: 'claire_adapter' },
    auth: [{ id: 'local', type: 'none', provider: 'fixture', requestedScopes: [] }],
    capabilities: [
      {
        id: 'demo.echo',
        kind: 'action',
        title: 'Echo',
        description: 'Return the fixture payload.',
        inputSchema: { type: 'object' },
        outputSchema: { type: 'object' },
        risk: 'read',
        approval: 'never',
        reversible: true,
        idempotency: true,
      },
    ],
    triggers: [{ id: 'manual', event: 'manual', supportedActions: ['demo.echo'] }],
    dataHandling: { receivesRawMessages: false, retention: 'none' },
  },
  handlers: {
    async 'demo.echo'(request) {
      return { ok: true, output: request.input, receiptId: createReceiptId('${slug}') };
    },
  },
});
`,
);

console.log(`Created ${dir}`);
console.log('Run: bun run test:plugins');
