// SPDX-License-Identifier: Apache-2.0
/*
 * Discovers documentation modules and generates the registry the site routes
 * from.
 *
 * Documentation is TypeScript, so the compiler already enforces the shape of
 * `meta` — section, status, and roadmap stage are union types. This script
 * covers what types cannot: date formatting, duplicate routes, and every
 * internal `/docs/...` reference resolving to a document that exists.
 */
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const websiteRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const contentRoot = join(websiteRoot, 'src', 'content', 'docs');
const generatedRoot = join(websiteRoot, 'src', 'generated');

type ContentFile = { absolute: string; slug: string; source: string };

async function discover(directory: string): Promise<Array<{ absolute: string; slug: string }>> {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map(async (entry) => {
      const absolute = join(directory, entry.name);
      if (entry.isDirectory()) return discover(absolute);
      if (entry.isFile() && entry.name.endsWith('.tsx')) {
        const slug = relative(contentRoot, absolute).replace(/\.tsx$/, '').split('\\').join('/');
        return [{ absolute, slug }];
      }
      return [];
    }),
  );
  return nested.flat().sort((a, b) => a.slug.localeCompare(b.slug));
}

const failures: string[] = [];

function fail(slug: string, message: string) {
  failures.push(`${slug}.tsx: ${message}`);
}

function readMetaField(source: string, field: string): string | undefined {
  const match = source.match(new RegExp(`\\b${field}:\\s*'([^']*)'`));
  return match?.[1];
}

const files: ContentFile[] = [];
for (const file of await discover(contentRoot)) {
  files.push({ ...file, source: await readFile(file.absolute, 'utf8') });
}

if (!files.length) {
  console.error('No documentation modules found in src/content/docs.');
  process.exit(1);
}

const slugs = new Set(files.map((file) => file.slug));
const routes = new Set([...slugs].map((slug) => `/docs/${slug}`));

for (const file of files) {
  if (!/export\s+const\s+meta\s*:\s*DocMeta\s*=/.test(file.source)) {
    fail(file.slug, 'must `export const meta: DocMeta = { … }`');
  }
  if (!/export\s+default\s+function/.test(file.source)) {
    fail(file.slug, 'must have a default-exported component');
  }

  const lastReviewed = readMetaField(file.source, 'lastReviewed');
  if (!lastReviewed) {
    fail(file.slug, 'missing `lastReviewed`');
  } else if (!/^\d{4}-\d{2}-\d{2}$/.test(lastReviewed)) {
    fail(file.slug, `lastReviewed must use YYYY-MM-DD, got \`${lastReviewed}\``);
  } else if (Number.isNaN(Date.parse(lastReviewed))) {
    fail(file.slug, `lastReviewed is not a real date: \`${lastReviewed}\``);
  }

  // Any `/docs/...` literal anywhere in the module — `href`, `to`, `related` —
  // has to resolve. This is the check that used to live in the Markdown link
  // validator and is the main thing keeping cross-references honest.
  for (const match of file.source.matchAll(/'(\/docs\/[^']*)'/g)) {
    const target = match[1].replace(/#.*$/, '');
    if (target === '/docs' || target === '/docs/all') continue;
    if (!routes.has(target)) fail(file.slug, `link to a document that does not exist: ${target}`);
  }
}

if (failures.length) {
  console.error(`\nDocumentation validation failed (${failures.length}):\n`);
  for (const failure of failures) console.error(`  ✗ ${failure}`);
  console.error('');
  process.exit(1);
}

function identifier(slug: string, index: number) {
  return `doc${index}_${slug.replace(/[^a-zA-Z0-9]/g, '_')}`;
}

const imports = files
  .map((file, index) => `import * as ${identifier(file.slug, index)} from '@/content/docs/${file.slug}';`)
  .join('\n');

const entries = files
  .map((file, index) => `  '${file.slug}': ${identifier(file.slug, index)},`)
  .join('\n');

const registry = `// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/build-docs.ts — do not edit.
import type { DocModule } from '@/lib/docs-types';

${imports}

export const docModules = {
${entries}
} satisfies Record<string, DocModule>;

export type DocSlug = keyof typeof docModules;
`;

await mkdir(generatedRoot, { recursive: true });
await writeFile(join(generatedRoot, 'docs-registry.ts'), registry);

console.log(`Registered ${files.length} documentation modules.`);
